### ISSUE TITLE
Minimum offtime not saved

### ISSUE THREAD

**Issue by MSmeets94** [MMMZZZZ/Syntherrupter#11]
### Version
v4.1.2

### Issue
The minimum offtime is set back to "0" after a powercycle. I noticed this two times while testing out the syntherrupter. I didn't check if it only happens under certain circumstances. 

--
Btw, Thank you for this project. Works great so far!

**Comment by MMMZZZZ** [comment]
Thank you for the bug report!

I was able to reproduce and fix the issue. It was actually only a display issue, meaning the minimum offtime worked just fine but on startup the display wouldn't get updated with the right values. 
The fix is part of the new v4.1.3 [release](https://github.com/MMMZZZZ/Syntherrupter/releases).

Kind regards,
Max
