### ISSUE TITLE
Syntherrupter v4.2.0 beta3 - simple mode outputs not in sync at low Hz

### ISSUE THREAD

**Issue by MadsBarnkob** [MMMZZZZ/Syntherrupter#28]
https://www.youtube.com/watch?v=kB5LqUTlLgs

See video where it can be seen and heard, that not all 6 outputs run synchronously in simple mode. It seems like 1-3 is in sync, while 4 to 6 is being "scanned".

**Comment by MMMZZZZ** [comment]
Noticed this recently, too. With the unbuffered outputs it could have been possible to fix it somehow but with each coil having independent buffers and timers I think it’s not possible to sync them. 

The main reason for this is that the buffers are processed by interrupt service routines (ISR) which take a little less than 2us. Because of interrupt priorities this means that the ISR of the last of the six timers may be delayed by as much as 5*2us. This is causes all timers to drift with respect to each other and I have no possibility to compensate for it. 

My only suggestion would be to drive all coils by the same output of Syntherrupter in such cases. Can’t remember your switch configuration but it might be possible for you. 

Regards,
Max
